// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('task7', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('task7', async function() {
    // Test name: task7
    // Step # | name | target | value
    // 1 | open | https://www.softwaretestinghelp.com/ | 
    await driver.get("https://www.softwaretestinghelp.com/")
    // 2 | click | linkText=Home | 
    await driver.findElement(By.linkText("Home")).click()
  })
})
